
// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phcfzupckgmgufmmhbrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoY2Z6dXBja2dtZ3VmbW1oYnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTIwNDgsImV4cCI6MjA2MDgyODA0OH0.rI7VP7YwXwpOWw-IMnGGwhBSU8VaPdyKCjWcwzIL9qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   realtime: {
//     params: {
//       eventsPerSecond: 10
//     }
//   }
// });

// Initialize realtime subscriptions for the tables we need
export const initializeRealtimeSubscriptions = () => {
  // Enable realtime for specific tables
  supabase.channel('public:donor_profiles')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'donor_profiles' }, (payload) => {
      console.log('Change received!', payload);
    })
    .subscribe();
    
  supabase.channel('public:blood_inventory')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'blood_inventory' }, (payload) => {
      console.log('Inventory change!', payload);
    })
    .subscribe();
    
  supabase.channel('public:donation_appointments')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'donation_appointments' }, (payload) => {
      console.log('Appointment change!', payload);
    })
    .subscribe();
};
